//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFRL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SingularityEdmx : DbContext
    {
        public SingularityEdmx()
            : base("name=SingularityEdmx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_main_menu> tb_main_menu { get; set; }
        public virtual DbSet<tb_sub_menu> tb_sub_menu { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    }
}
