//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFRL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_main_menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_main_menu()
        {
            this.tb_sub_menu = new HashSet<tb_sub_menu>();
        }
    
        public int Id { get; set; }
        public string parent_menu_text { get; set; }
        public string parent_icon_class { get; set; }
        public Nullable<int> display_order { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_sub_menu> tb_sub_menu { get; set; }
    }
}
