//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFRL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sub_menu
    {
        public int Id { get; set; }
        public string sub_menu_text { get; set; }
        public string sub_icon_class { get; set; }
        public string page_url { get; set; }
        public Nullable<int> main_menu_id { get; set; }
    
        public virtual tb_main_menu tb_main_menu { get; set; }
    }
}
