//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFRL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserMobile { get; set; }
        public string UserEmail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UserImageFile { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> IsCreatePermission { get; set; }
        public Nullable<bool> IsEditPermission { get; set; }
        public Nullable<bool> IsViewPermission { get; set; }
        public Nullable<bool> IsDeletePermission { get; set; }
        public string Token { get; set; }
    }
}
